#!/bin/bash
set -e

# 1. Start Virtual Frame Buffer (Xvfb)
rm -f /tmp/.X99-lock /tmp/.X11-unix/X99
echo "Starting Xvfb on display ${DISPLAY:-:99}..."
Xvfb ${DISPLAY:-:99} -screen 0 1280x800x24 &
sleep 2

# 2. Start Fluxbox Window Manager (required to keep display active and window placements)
echo "Starting Fluxbox..."
fluxbox &
sleep 1

# 3. Start VNC Server (x11vnc)
echo "Starting x11vnc..."
if [ -n "$VNC_PASSWORD" ]; then
  # Create password file
  mkdir -p ~/.vnc
  x11vnc -storepw "$VNC_PASSWORD" ~/.vnc/passwd
  x11vnc -display ${DISPLAY:-:99} -rfbport 5900 -rfbauth ~/.vnc/passwd -forever -quiet &
else
  x11vnc -display ${DISPLAY:-:99} -rfbport 5900 -nopw -forever -quiet &
fi
sleep 1

# 4. Start noVNC Websocket Bridge
if [ "${NOVNC_ENABLE:-true}" = "true" ]; then
  echo "Starting noVNC websockify bridge on port 6080 -> 5900..."
  websockify --web /usr/share/novnc 6080 localhost:5900 &
fi
sleep 1

# 4b. Inject user.js into Camoufox profile to fix Microsoft SSO CORS issues
#     Camoufox has strict privacy settings that block cross-origin cookies needed for M365 login
PROFILE_DIR="${CAMOUFOX_USER_DATA_DIR:-/app/data/camoufox_profile}"
mkdir -p "$PROFILE_DIR"
cat > "$PROFILE_DIR/user.js" << 'USERJS'
// Microsoft SSO CORS Fix — auto-generated by docker-entrypoint.sh
// Camoufox's strict privacy settings block Microsoft SSO cross-origin flows

// Disable Enhanced Tracking Protection (blocks Microsoft SSO cookies)
user_pref("privacy.trackingprotection.enabled", false);
user_pref("privacy.trackingprotection.socialtracking.enabled", false);
user_pref("privacy.trackingprotection.fingerprinting.enabled", false);
user_pref("privacy.trackingprotection.cryptomining.enabled", false);

// Allow cross-site cookies (needed for Microsoft SSO iframe/redirect flow)
user_pref("network.cookie.cookieBehavior", 0);
user_pref("network.cookie.cookieBehavior.pbmode", 0);

// Disable Total Cookie Protection (breaks SSO across microsoft.com subdomains)
user_pref("privacy.partition.network_state", false);
user_pref("network.cookie.thirdparty.sessionOnly", false);
user_pref("network.cookie.thirdparty.nonsecureSessionOnly", false);

// Allow popups from Microsoft SSO
user_pref("dom.popup_maximum", 100);

// Disable HTTPS-only mode (causes SSO redirect loops)
user_pref("dom.security.https_only_mode", false);
user_pref("dom.security.https_only_mode_pbm", false);

// Disable fingerprinting resistance (causes issues with Microsoft UI detection)
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts", false);

// Allow referrer headers (required by Microsoft SSO)
user_pref("network.http.referer.defaultPolicy", 3);
user_pref("network.http.referer.defaultPolicy.pbmode", 3);

// Keep session alive
user_pref("browser.sessionstore.resume_from_crash", true);
USERJS
echo "Camoufox user.js written to $PROFILE_DIR/user.js (Microsoft SSO CORS fix)"

# 5. Start FastAPI Proxy Application
echo "Starting FastAPI Application on ${HOST:-0.0.0.0}:${PORT:-8000}..."
exec uvicorn app.main:app --host "${HOST:-0.0.0.0}" --port "${PORT:-8000}"
